
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: instragram_database_dev

test:
  <<: *default
  database: instragram_database_test

production:
  <<: *default
  adapter: postgresql
  url: <%= ENV["DATABASE_URL"] %>
  database: instragram_database_pro

